Repository zenml-io/vscode-tutorial-extension, pull requests merged in 2025-06, with the labels that each got.

#7 Integrate daily pipeline health GitHub Action with Discord failure alerts
  .github/workflows/test-pipelines.yml
  README.md
Labels: ci/cd

#10 Add button to view dashboard after successful pipeline run / completion
  .claude/settings.local.json
  assets/main.css
  assets/main.js
  src/tutorialOrchestrator.ts
  src/utils/codeRunner.ts
  utils.py
Labels: enhancement

#11 Add GitHub Actions workflow for building VSCode extensions
  .github/workflows/build-extensions.yml
Labels: enhancement, ci/cd
